### ISSUE TITLE
mmpdb transform --min-constant-size N - AttributeError: 'Fragmentation' object has no attribute 'num_variable_heavies'

### ISSUE THREAD

**Issue by Niaev** [rdkit/mmpdb#21]
On Windows, the options `--min-variable-size` and `--min-constant-size` of **transform** command aren't working. It is saying that, in the line 909 in `mmpdblib/analysis_algorithms.py`, a Fragmentation object has no attribute 'num_variable_heavies'.

I'm on Windows 10 and using Anaconda Prompt, mmpdb works fine.

I tried the same command on Linux and it worked, but I think it's relevant to report the issue on Windows.

```
(base) C:\Users\me\Desktop\mmpdb-2.1>python mmpdb transform --smiles CC=CC=CC=O --min-variable-size 5 my_data.mmpdb
Traceback (most recent call last):
  File "mmpdb", line 10, in <module>
    commandline.main()
  File "C:\Users\me\Desktop\mmpdb-2.1\mmpdblib\commandline.py", line 988, in main
    parsed_args.command(parsed_args.subparser, parsed_args)
  File "C:\Users\me\Desktop\mmpdb-2.1\mmpdblib\commandline.py", line 678, in transform_command
    do_analysis.transform_command(parser, args)
  File "C:\Users\me\Desktop\mmpdb-2.1\mmpdblib\do_analysis.py", line 116, in transform_command
    explain = explain,
  File "C:\Users\me\Desktop\mmpdb-2.1\mmpdblib\analysis_algorithms.py", line 764, in transform
    cursor=cursor, explain=explain)
  File "C:\Users\me\Desktop\mmpdb-2.1\mmpdblib\analysis_algorithms.py", line 909, in make_transform
    if min_variable_size and frag.num_variable_heavies < min_variable_size:
AttributeError: 'Fragmentation' object has no attribute 'num_variable_heavies'
```

**Comment by KramerChristian** [comment]
Dear Niaev,

thank you for the bug report. I will look into it, I just cannot promise when exactly.

Best regards,
Christian
